import { loginScreen, signupScreen, forgotPasswordScreen, emailVerificationScreen } from "./wireframe";

const SCREEN_GAP = 300;

export const authFlowTemplate = {
  screens: [
    {
      id: "tpl_auth_login",
      name: "Login",
      x: 0,
      y: 0,
      width: 220,
      imageData: loginScreen(),
      description: "User login screen with email and password fields",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_auth_hs_login_btn",
          label: "Log In Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 69, w: 82, h: 9,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/auth/login",
          apiMethod: "POST",
          requestSchema: '{ "email": "string", "password": "string" }',
          responseSchema: '{ "token": "string", "user": "object" }',
          documentId: null,
          conditions: [],
          onSuccessAction: "navigate",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "Navigate to home screen",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show error message",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_auth_hs_forgot",
          label: "Forgot Password Link",
          elementType: "text",
          interactionType: "tap",
          x: 22, y: 83, w: 56, h: 5,
          action: "navigate",
          targetScreenId: "tpl_auth_forgot",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_auth_hs_signup_link",
          label: "Sign Up Link",
          elementType: "text",
          interactionType: "tap",
          x: 10, y: 89, w: 80, h: 5,
          action: "navigate",
          targetScreenId: "tpl_auth_signup",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_auth_signup",
      name: "Sign Up",
      x: SCREEN_GAP,
      y: 0,
      width: 220,
      imageData: signupScreen(),
      description: "User registration with name, email, and password",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_auth_hs_create_btn",
          label: "Create Account Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 72, w: 82, h: 9,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/auth/register",
          apiMethod: "POST",
          requestSchema: '{ "name": "string", "email": "string", "password": "string" }',
          responseSchema: '{ "token": "string", "user": "object" }',
          documentId: null,
          conditions: [],
          onSuccessAction: "navigate",
          onSuccessTargetId: "tpl_auth_verify",
          onSuccessCustomDesc: "Navigate to email verification",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show validation errors",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_auth_hs_login_link",
          label: "Log In Link",
          elementType: "text",
          interactionType: "tap",
          x: 10, y: 86, w: 80, h: 5,
          action: "navigate",
          targetScreenId: "tpl_auth_login",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_auth_forgot",
      name: "Forgot Password",
      x: 0,
      y: 480,
      width: 220,
      imageData: forgotPasswordScreen(),
      description: "Password reset request with email input",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_auth_hs_reset_btn",
          label: "Send Reset Link Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 54, w: 82, h: 9,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/auth/reset-password",
          apiMethod: "POST",
          requestSchema: '{ "email": "string" }',
          responseSchema: '{ "message": "string" }',
          documentId: null,
          conditions: [],
          onSuccessAction: "navigate",
          onSuccessTargetId: "tpl_auth_verify",
          onSuccessCustomDesc: "Navigate to email verification",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show error message",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_auth_verify",
      name: "Email Verification",
      x: SCREEN_GAP,
      y: 480,
      width: 220,
      imageData: emailVerificationScreen(),
      description: "Email verification confirmation screen",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_auth_hs_resend",
          label: "Resend Email",
          elementType: "text",
          interactionType: "tap",
          x: 22, y: 77, w: 56, h: 5,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/auth/resend-verification",
          apiMethod: "POST",
          requestSchema: '{ "email": "string" }',
          responseSchema: '{ "message": "string" }',
          documentId: null,
          conditions: [],
          onSuccessAction: "custom",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "Show success toast",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show error message",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "",
          transitionLabel: "",
        },
      ],
    },
  ],
  connections: [
    {
      id: "tpl_auth_conn_to_signup",
      fromScreenId: "tpl_auth_login",
      toScreenId: "tpl_auth_signup",
      hotspotId: "tpl_auth_hs_signup_link",
      label: "Sign Up",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_auth_conn_to_forgot",
      fromScreenId: "tpl_auth_login",
      toScreenId: "tpl_auth_forgot",
      hotspotId: "tpl_auth_hs_forgot",
      label: "Forgot Password",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_auth_conn_signup_to_verify",
      fromScreenId: "tpl_auth_signup",
      toScreenId: "tpl_auth_verify",
      hotspotId: "tpl_auth_hs_create_btn",
      label: "Verify Email",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "api-success",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_auth_conn_forgot_to_verify",
      fromScreenId: "tpl_auth_forgot",
      toScreenId: "tpl_auth_verify",
      hotspotId: "tpl_auth_hs_reset_btn",
      label: "Check Email",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "api-success",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_auth_conn_signup_to_login",
      fromScreenId: "tpl_auth_signup",
      toScreenId: "tpl_auth_login",
      hotspotId: "tpl_auth_hs_login_link",
      label: "Back to Login",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
  ],
  documents: [],
};
