import { productListScreen, productDetailScreen, cartScreen, checkoutScreen } from "./wireframe";

const SCREEN_GAP = 300;

export const ecommerceFlowTemplate = {
  screens: [
    {
      id: "tpl_eco_product_list",
      name: "Product List",
      x: 0,
      y: 0,
      width: 220,
      imageData: productListScreen(),
      description: "Browsable product catalog with grid/list view",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_eco_hs_product_item",
          label: "Product Item",
          elementType: "card",
          interactionType: "tap",
          x: 9, y: 30, w: 82, h: 25,
          action: "navigate",
          targetScreenId: "tpl_eco_product_detail",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_eco_hs_cart_tab",
          label: "Cart Tab",
          elementType: "button",
          interactionType: "tap",
          x: 70, y: 90, w: 20, h: 8,
          action: "navigate",
          targetScreenId: "tpl_eco_cart",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_eco_hs_load_products",
          label: "Load Products",
          elementType: "container",
          interactionType: "tap",
          x: 5, y: 15, w: 90, h: 5,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/products",
          apiMethod: "GET",
          requestSchema: "",
          responseSchema: '{ "products": [{ "id": "string", "name": "string", "price": "number", "image": "string" }] }',
          documentId: null,
          conditions: [],
          onSuccessAction: "custom",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "Populate product list",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show error message",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_eco_product_detail",
      name: "Product Detail",
      x: SCREEN_GAP,
      y: 0,
      width: 220,
      imageData: productDetailScreen(),
      description: "Detailed product view with images, description, and add to cart",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_eco_hs_add_to_cart",
          label: "Add to Cart",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 80, w: 82, h: 9,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/cart/add",
          apiMethod: "POST",
          requestSchema: '{ "productId": "string", "quantity": "number" }',
          responseSchema: '{ "cart": { "items": "array", "total": "number" } }',
          documentId: null,
          conditions: [],
          onSuccessAction: "navigate",
          onSuccessTargetId: "tpl_eco_cart",
          onSuccessCustomDesc: "Navigate to cart",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show error message",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_eco_cart",
      name: "Cart",
      x: SCREEN_GAP * 2,
      y: 0,
      width: 220,
      imageData: cartScreen(),
      description: "Shopping cart with item list, quantities, and total",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_eco_hs_checkout_btn",
          label: "Checkout Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 82, w: 82, h: 9,
          action: "navigate",
          targetScreenId: "tpl_eco_checkout",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_eco_hs_back",
          label: "Back Navigation",
          elementType: "button",
          interactionType: "tap",
          x: 5, y: 3, w: 15, h: 6,
          action: "navigate",
          targetScreenId: "tpl_eco_product_list",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "pop",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_eco_checkout",
      name: "Checkout",
      x: SCREEN_GAP * 3,
      y: 0,
      width: 220,
      imageData: checkoutScreen(),
      description: "Checkout form with shipping, payment, and order summary",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_eco_hs_place_order",
          label: "Place Order",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 82, w: 82, h: 9,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/orders",
          apiMethod: "POST",
          requestSchema: '{ "items": "array", "shippingAddress": "object", "paymentMethod": "object" }',
          responseSchema: '{ "orderId": "string", "status": "string", "total": "number" }',
          documentId: null,
          conditions: [],
          onSuccessAction: "custom",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "Show order confirmation",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show error message",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "",
          transitionLabel: "",
        },
      ],
    },
  ],
  connections: [
    {
      id: "tpl_eco_conn_list_to_detail",
      fromScreenId: "tpl_eco_product_list",
      toScreenId: "tpl_eco_product_detail",
      hotspotId: "tpl_eco_hs_product_item",
      label: "View Product",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_eco_conn_detail_to_cart",
      fromScreenId: "tpl_eco_product_detail",
      toScreenId: "tpl_eco_cart",
      hotspotId: "tpl_eco_hs_add_to_cart",
      label: "Add to Cart",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "api-success",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_eco_conn_cart_to_checkout",
      fromScreenId: "tpl_eco_cart",
      toScreenId: "tpl_eco_checkout",
      hotspotId: "tpl_eco_hs_checkout_btn",
      label: "Checkout",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
  ],
  documents: [],
};
