export const TEMPLATES = [
  {
    id: "auth",
    name: "Authentication",
    description: "Login, signup, forgot password, and email verification screens with API integration",
    category: "Core",
    screenCount: 4,
    getData: () => import("./authFlow.js").then((m) => m.authFlowTemplate),
  },
  {
    id: "onboarding",
    name: "Onboarding",
    description: "Welcome, permissions, tutorial, and get started screens for new users",
    category: "Core",
    screenCount: 4,
    getData: () => import("./onboardingFlow.js").then((m) => m.onboardingFlowTemplate),
  },
  {
    id: "settings",
    name: "Settings",
    description: "Profile editing, preferences, and notification settings screens",
    category: "Core",
    screenCount: 3,
    getData: () => import("./settingsFlow.js").then((m) => m.settingsFlowTemplate),
  },
  {
    id: "tab-bar",
    name: "Tab Bar App",
    description: "Four-tab navigation with Home, Search, Profile, and Settings screens",
    category: "Navigation",
    screenCount: 4,
    getData: () => import("./tabBarFlow.js").then((m) => m.tabBarFlowTemplate),
  },
  {
    id: "ecommerce",
    name: "E-Commerce",
    description: "Product listing, detail, cart, and checkout flow with API endpoints",
    category: "Commerce",
    screenCount: 4,
    getData: () => import("./ecommerceFlow.js").then((m) => m.ecommerceFlowTemplate),
  },
  {
    id: "social-feed",
    name: "Social Feed",
    description: "Feed, post detail, create post, and user profile screens",
    category: "Social",
    screenCount: 4,
    getData: () => import("./socialFeedFlow.js").then((m) => m.socialFeedFlowTemplate),
  },
];
