import { welcomeScreen, permissionsScreen, tutorialScreen, getStartedScreen } from "./wireframe";

export const onboardingFlowTemplate = {
  screens: [
    {
      id: "tpl_onb_welcome",
      name: "Welcome",
      x: 0,
      y: 0,
      width: 220,
      imageData: welcomeScreen(),
      description: "Welcome screen introducing the app to new users",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_onb_hs_get_started",
          label: "Get Started Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 75, w: 82, h: 9,
          action: "navigate",
          targetScreenId: "tpl_onb_permissions",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_onb_hs_skip",
          label: "Skip Link",
          elementType: "text",
          interactionType: "tap",
          x: 22, y: 88, w: 56, h: 5,
          action: "navigate",
          targetScreenId: "tpl_onb_getstarted",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_onb_permissions",
      name: "Permissions",
      x: 300,
      y: 0,
      width: 220,
      imageData: permissionsScreen(),
      description: "Request necessary app permissions from the user",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_onb_hs_continue",
          label: "Continue Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 75, w: 82, h: 9,
          action: "navigate",
          targetScreenId: "tpl_onb_tutorial",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_onb_tutorial",
      name: "Tutorial",
      x: 600,
      y: 0,
      width: 220,
      imageData: tutorialScreen(),
      description: "Brief tutorial highlighting key app features",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_onb_hs_next",
          label: "Next Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 75, w: 82, h: 9,
          action: "navigate",
          targetScreenId: "tpl_onb_getstarted",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_onb_getstarted",
      name: "Get Started",
      x: 900,
      y: 0,
      width: 220,
      imageData: getStartedScreen(),
      description: "Final onboarding screen prompting user to begin using the app",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_onb_hs_letsgo",
          label: "Let's Go Button",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 75, w: 82, h: 9,
          action: "navigate",
          targetScreenId: null,
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
  ],
  connections: [
    {
      id: "tpl_onb_conn_welcome_to_permissions",
      fromScreenId: "tpl_onb_welcome",
      toScreenId: "tpl_onb_permissions",
      hotspotId: "tpl_onb_hs_get_started",
      label: "Get Started",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_onb_conn_welcome_to_getstarted",
      fromScreenId: "tpl_onb_welcome",
      toScreenId: "tpl_onb_getstarted",
      hotspotId: "tpl_onb_hs_skip",
      label: "Skip",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_onb_conn_permissions_to_tutorial",
      fromScreenId: "tpl_onb_permissions",
      toScreenId: "tpl_onb_tutorial",
      hotspotId: "tpl_onb_hs_continue",
      label: "Continue",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_onb_conn_tutorial_to_getstarted",
      fromScreenId: "tpl_onb_tutorial",
      toScreenId: "tpl_onb_getstarted",
      hotspotId: "tpl_onb_hs_next",
      label: "Next",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
  ],
  documents: [],
};
