import { profileSettingsScreen, preferencesScreen, notificationsScreen } from "./wireframe";

export const settingsFlowTemplate = {
  screens: [
    {
      id: "tpl_set_profile",
      name: "Profile",
      x: 0,
      y: 0,
      width: 220,
      imageData: profileSettingsScreen(),
      description: "Profile settings screen for editing user information",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_set_hs_save_profile",
          label: "Save Changes",
          elementType: "button",
          interactionType: "tap",
          x: 9, y: 80, w: 82, h: 9,
          action: "api",
          targetScreenId: null,
          apiEndpoint: "/api/user/profile",
          apiMethod: "PUT",
          requestSchema: '{ "name": "string", "email": "string", "avatar": "string" }',
          responseSchema: '{ "user": "object", "message": "string" }',
          documentId: null,
          conditions: [],
          onSuccessAction: "custom",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "Show success toast",
          onErrorAction: "custom",
          onErrorTargetId: null,
          onErrorCustomDesc: "Show error message",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_set_preferences",
      name: "Preferences",
      x: 300,
      y: 0,
      width: 220,
      imageData: preferencesScreen(),
      description: "App preferences with theme, language, and display settings",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_set_hs_dark_mode",
          label: "Dark Mode Toggle",
          elementType: "button",
          interactionType: "tap",
          x: 60, y: 30, w: 30, h: 8,
          action: "none",
          targetScreenId: null,
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "Toggle dark mode on/off and persist preference locally",
          transitionType: "",
          transitionLabel: "",
        },
        {
          id: "tpl_set_hs_language",
          label: "Language Selector",
          elementType: "button",
          interactionType: "tap",
          x: 60, y: 45, w: 30, h: 8,
          action: "none",
          targetScreenId: null,
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "Open language picker to change app locale",
          transitionType: "",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_set_notifications",
      name: "Notifications",
      x: 600,
      y: 0,
      width: 220,
      imageData: notificationsScreen(),
      description: "Notification preferences for push, email, and in-app alerts",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_set_hs_push_toggle",
          label: "Push Notifications Toggle",
          elementType: "button",
          interactionType: "tap",
          x: 60, y: 35, w: 30, h: 8,
          action: "none",
          targetScreenId: null,
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "Toggle push notifications on/off",
          transitionType: "",
          transitionLabel: "",
        },
      ],
    },
  ],
  connections: [],
  documents: [],
};
