import { MERGE_GAP } from "../constants";
import { profileSettingsScreen, preferencesScreen, notificationsScreen } from "./wireframe";
import { makeHotspot } from "./makeHotspot";

export const settingsFlowTemplate = {
  screens: [
    {
      id: "tpl_set_profile",
      name: "Profile",
      x: 0,
      y: 0,
      width: 220,
      imageData: profileSettingsScreen(),
      description: "Profile settings screen for editing user information",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({
          id: "tpl_set_hs_save_profile",
          label: "Save Changes",
          x: 9, y: 80, w: 82, h: 9,
          action: "api",
          apiEndpoint: "/api/user/profile",
          apiMethod: "PUT",
          requestSchema: '{ "name": "string", "email": "string", "avatar": "string" }',
          responseSchema: '{ "user": "object", "message": "string" }',
          onSuccessAction: "custom",
          onSuccessCustomDesc: "Show success toast",
          onErrorAction: "custom",
          onErrorCustomDesc: "Show error message",
        }),
      ],
    },
    {
      id: "tpl_set_preferences",
      name: "Preferences",
      x: MERGE_GAP,
      y: 0,
      width: 220,
      imageData: preferencesScreen(),
      description: "App preferences with theme, language, and display settings",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({
          id: "tpl_set_hs_dark_mode",
          label: "Dark Mode Toggle",
          x: 60, y: 30, w: 30, h: 8,
          action: "none",
          customDescription: "Toggle dark mode on/off and persist preference locally",
        }),
        makeHotspot({
          id: "tpl_set_hs_language",
          label: "Language Selector",
          x: 60, y: 45, w: 30, h: 8,
          action: "none",
          customDescription: "Open language picker to change app locale",
        }),
      ],
    },
    {
      id: "tpl_set_notifications",
      name: "Notifications",
      x: 2 * MERGE_GAP,
      y: 0,
      width: 220,
      imageData: notificationsScreen(),
      description: "Notification preferences for push, email, and in-app alerts",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({
          id: "tpl_set_hs_push_toggle",
          label: "Push Notifications Toggle",
          x: 60, y: 35, w: 30, h: 8,
          action: "none",
          customDescription: "Toggle push notifications on/off",
        }),
      ],
    },
  ],
  connections: [],
  documents: [],
};
