import { feedScreen, postDetailScreen, createPostScreen, userProfileScreen } from "./wireframe";
import { makeHotspot } from "./makeHotspot";
import { MERGE_GAP } from "../constants";

export const socialFeedFlowTemplate = {
  screens: [
    {
      id: "tpl_soc_feed",
      name: "Feed",
      x: 0,
      y: 0,
      width: 220,
      imageData: feedScreen(),
      description: "Main social feed showing posts from followed users",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({
          id: "tpl_soc_hs_post_item",
          label: "Post Item",
          elementType: "card",
          x: 5, y: 25, w: 90, h: 25,
          targetScreenId: "tpl_soc_post_detail",
          transitionType: "push",
        }),
        makeHotspot({
          id: "tpl_soc_hs_create_post",
          label: "Create Post",
          x: 75, y: 88, w: 20, h: 8,
          targetScreenId: "tpl_soc_create_post",
          transitionType: "push",
        }),
        makeHotspot({
          id: "tpl_soc_hs_user_avatar",
          label: "User Avatar",
          elementType: "image",
          x: 5, y: 26, w: 10, h: 5,
          targetScreenId: "tpl_soc_user_profile",
          transitionType: "push",
        }),
        makeHotspot({
          id: "tpl_soc_hs_feed_api",
          label: "Load Feed",
          elementType: "container",
          x: 5, y: 15, w: 90, h: 75,
          action: "api",
          apiEndpoint: "/api/feed",
          apiMethod: "GET",
          responseSchema: '{ "posts": "array", "nextCursor": "string" }',
          onSuccessAction: "custom",
          onSuccessCustomDesc: "Populate feed with posts",
          onErrorAction: "custom",
          onErrorCustomDesc: "Show error state",
        }),
      ],
    },
    {
      id: "tpl_soc_post_detail",
      name: "Post Detail",
      x: MERGE_GAP,
      y: 0,
      width: 220,
      imageData: postDetailScreen(),
      description: "Detailed view of a single post with comments",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({
          id: "tpl_soc_hs_comment_input",
          label: "Comment Input",
          elementType: "input",
          x: 5, y: 85, w: 90, h: 8,
          action: "api",
          apiEndpoint: "/api/posts/{id}/comments",
          apiMethod: "POST",
          requestSchema: '{ "text": "string" }',
          responseSchema: '{ "comment": "object" }',
          onSuccessAction: "custom",
          onSuccessCustomDesc: "Append comment to list",
          onErrorAction: "custom",
          onErrorCustomDesc: "Show error message",
        }),
        makeHotspot({
          id: "tpl_soc_hs_user_name",
          label: "User Name",
          elementType: "text",
          x: 15, y: 8, w: 40, h: 5,
          targetScreenId: "tpl_soc_user_profile",
          transitionType: "push",
        }),
      ],
    },
    {
      id: "tpl_soc_create_post",
      name: "Create Post",
      x: 0,
      y: 480,
      width: 220,
      imageData: createPostScreen(),
      description: "Compose and share a new post with text and media",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({
          id: "tpl_soc_hs_share_btn",
          label: "Share Button",
          x: 70, y: 5, w: 25, h: 8,
          action: "api",
          apiEndpoint: "/api/posts",
          apiMethod: "POST",
          requestSchema: '{ "text": "string", "media": "array" }',
          responseSchema: '{ "post": "object" }',
          onSuccessAction: "navigate",
          onSuccessTargetId: "tpl_soc_feed",
          onSuccessCustomDesc: "Navigate back to feed",
          onErrorAction: "custom",
          onErrorCustomDesc: "Show error message",
          transitionType: "push",
        }),
      ],
    },
    {
      id: "tpl_soc_user_profile",
      name: "User Profile",
      x: MERGE_GAP,
      y: 480,
      width: 220,
      imageData: userProfileScreen(),
      description: "User profile with bio, stats, and post history",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({
          id: "tpl_soc_hs_follow_btn",
          label: "Follow Button",
          x: 60, y: 20, w: 30, h: 8,
          action: "api",
          apiEndpoint: "/api/users/{id}/follow",
          apiMethod: "POST",
          responseSchema: '{ "following": "boolean" }',
          onSuccessAction: "custom",
          onSuccessCustomDesc: "Toggle follow state",
          onErrorAction: "custom",
          onErrorCustomDesc: "Show error message",
        }),
      ],
    },
  ],
  connections: [
    {
      id: "tpl_soc_conn_to_post_detail",
      fromScreenId: "tpl_soc_feed",
      toScreenId: "tpl_soc_post_detail",
      hotspotId: "tpl_soc_hs_post_item",
      label: "View Post",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_soc_conn_to_create_post",
      fromScreenId: "tpl_soc_feed",
      toScreenId: "tpl_soc_create_post",
      hotspotId: "tpl_soc_hs_create_post",
      label: "New Post",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_soc_conn_to_user_profile",
      fromScreenId: "tpl_soc_feed",
      toScreenId: "tpl_soc_user_profile",
      hotspotId: "tpl_soc_hs_user_avatar",
      label: "View Profile",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_soc_conn_detail_to_profile",
      fromScreenId: "tpl_soc_post_detail",
      toScreenId: "tpl_soc_user_profile",
      hotspotId: "tpl_soc_hs_user_name",
      label: "View Profile",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_soc_conn_create_to_feed",
      fromScreenId: "tpl_soc_create_post",
      toScreenId: "tpl_soc_feed",
      hotspotId: "tpl_soc_hs_share_btn",
      label: "Back to Feed",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "api-success",
      condition: "",
      conditionGroupId: null,
    },
  ],
  documents: [],
};
