import { homeTabScreen, searchTabScreen, profileTabScreen, settingsTabScreen } from "./wireframe";

export const tabBarFlowTemplate = {
  screens: [
    {
      id: "tpl_tab_home",
      name: "Home",
      x: 0,
      y: 0,
      width: 220,
      imageData: homeTabScreen(),
      description: "Main home tab with primary content feed",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_tab_hs_home_to_search",
          label: "Search Tab",
          elementType: "button",
          interactionType: "tap",
          x: 25, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_search",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_home_to_profile",
          label: "Profile Tab",
          elementType: "button",
          interactionType: "tap",
          x: 50, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_profile",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_home_to_settings",
          label: "Settings Tab",
          elementType: "button",
          interactionType: "tap",
          x: 75, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_settings",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_tab_search",
      name: "Search",
      x: 300,
      y: 0,
      width: 220,
      imageData: searchTabScreen(),
      description: "Search tab with search bar and results",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_tab_hs_search_to_home",
          label: "Home Tab",
          elementType: "button",
          interactionType: "tap",
          x: 0, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_home",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_search_to_profile",
          label: "Profile Tab",
          elementType: "button",
          interactionType: "tap",
          x: 50, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_profile",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_search_to_settings",
          label: "Settings Tab",
          elementType: "button",
          interactionType: "tap",
          x: 75, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_settings",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_tab_profile",
      name: "Profile",
      x: 600,
      y: 0,
      width: 220,
      imageData: profileTabScreen(),
      description: "User profile tab with account information",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_tab_hs_profile_to_home",
          label: "Home Tab",
          elementType: "button",
          interactionType: "tap",
          x: 0, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_home",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_profile_to_search",
          label: "Search Tab",
          elementType: "button",
          interactionType: "tap",
          x: 25, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_search",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_profile_to_settings",
          label: "Settings Tab",
          elementType: "button",
          interactionType: "tap",
          x: 75, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_settings",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
    {
      id: "tpl_tab_settings",
      name: "Settings",
      x: 900,
      y: 0,
      width: 220,
      imageData: settingsTabScreen(),
      description: "App settings tab with preferences and configuration",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        {
          id: "tpl_tab_hs_settings_to_home",
          label: "Home Tab",
          elementType: "button",
          interactionType: "tap",
          x: 0, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_home",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_settings_to_search",
          label: "Search Tab",
          elementType: "button",
          interactionType: "tap",
          x: 25, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_search",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
        {
          id: "tpl_tab_hs_settings_to_profile",
          label: "Profile Tab",
          elementType: "button",
          interactionType: "tap",
          x: 50, y: 88, w: 25, h: 8,
          action: "navigate",
          targetScreenId: "tpl_tab_profile",
          apiEndpoint: "",
          apiMethod: "",
          requestSchema: "",
          responseSchema: "",
          documentId: null,
          conditions: [],
          onSuccessAction: "",
          onSuccessTargetId: null,
          onSuccessCustomDesc: "",
          onErrorAction: "",
          onErrorTargetId: null,
          onErrorCustomDesc: "",
          dataFlow: [],
          onSuccessDataFlow: [],
          onErrorDataFlow: [],
          validation: null,
          tbd: false,
          tbdNote: "",
          customDescription: "",
          transitionType: "push",
          transitionLabel: "",
        },
      ],
    },
  ],
  connections: [
    {
      id: "tpl_tab_conn_home_to_search",
      fromScreenId: "tpl_tab_home",
      toScreenId: "tpl_tab_search",
      hotspotId: "tpl_tab_hs_home_to_search",
      label: "Search Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_home_to_profile",
      fromScreenId: "tpl_tab_home",
      toScreenId: "tpl_tab_profile",
      hotspotId: "tpl_tab_hs_home_to_profile",
      label: "Profile Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_home_to_settings",
      fromScreenId: "tpl_tab_home",
      toScreenId: "tpl_tab_settings",
      hotspotId: "tpl_tab_hs_home_to_settings",
      label: "Settings Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_search_to_home",
      fromScreenId: "tpl_tab_search",
      toScreenId: "tpl_tab_home",
      hotspotId: "tpl_tab_hs_search_to_home",
      label: "Home Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_search_to_profile",
      fromScreenId: "tpl_tab_search",
      toScreenId: "tpl_tab_profile",
      hotspotId: "tpl_tab_hs_search_to_profile",
      label: "Profile Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_search_to_settings",
      fromScreenId: "tpl_tab_search",
      toScreenId: "tpl_tab_settings",
      hotspotId: "tpl_tab_hs_search_to_settings",
      label: "Settings Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_profile_to_home",
      fromScreenId: "tpl_tab_profile",
      toScreenId: "tpl_tab_home",
      hotspotId: "tpl_tab_hs_profile_to_home",
      label: "Home Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_profile_to_search",
      fromScreenId: "tpl_tab_profile",
      toScreenId: "tpl_tab_search",
      hotspotId: "tpl_tab_hs_profile_to_search",
      label: "Search Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_profile_to_settings",
      fromScreenId: "tpl_tab_profile",
      toScreenId: "tpl_tab_settings",
      hotspotId: "tpl_tab_hs_profile_to_settings",
      label: "Settings Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_settings_to_home",
      fromScreenId: "tpl_tab_settings",
      toScreenId: "tpl_tab_home",
      hotspotId: "tpl_tab_hs_settings_to_home",
      label: "Home Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_settings_to_search",
      fromScreenId: "tpl_tab_settings",
      toScreenId: "tpl_tab_search",
      hotspotId: "tpl_tab_hs_settings_to_search",
      label: "Search Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_settings_to_profile",
      fromScreenId: "tpl_tab_settings",
      toScreenId: "tpl_tab_profile",
      hotspotId: "tpl_tab_hs_settings_to_profile",
      label: "Profile Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
  ],
  documents: [],
};
