import { MERGE_GAP } from "../constants";
import { makeHotspot } from "./makeHotspot";
import { homeTabScreen, searchTabScreen, profileTabScreen, settingsTabScreen } from "./wireframe";

export const tabBarFlowTemplate = {
  screens: [
    {
      id: "tpl_tab_home",
      name: "Home",
      x: 0,
      y: 0,
      width: 220,
      imageData: homeTabScreen(),
      description: "Main home tab with primary content feed",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({ id: "tpl_tab_hs_home_to_search", label: "Search Tab", x: 25, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_search", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_home_to_profile", label: "Profile Tab", x: 50, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_profile", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_home_to_settings", label: "Settings Tab", x: 75, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_settings", transitionType: "push" }),
      ],
    },
    {
      id: "tpl_tab_search",
      name: "Search",
      x: MERGE_GAP,
      y: 0,
      width: 220,
      imageData: searchTabScreen(),
      description: "Search tab with search bar and results",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({ id: "tpl_tab_hs_search_to_home", label: "Home Tab", x: 0, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_home", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_search_to_profile", label: "Profile Tab", x: 50, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_profile", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_search_to_settings", label: "Settings Tab", x: 75, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_settings", transitionType: "push" }),
      ],
    },
    {
      id: "tpl_tab_profile",
      name: "Profile",
      x: MERGE_GAP * 2,
      y: 0,
      width: 220,
      imageData: profileTabScreen(),
      description: "User profile tab with account information",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({ id: "tpl_tab_hs_profile_to_home", label: "Home Tab", x: 0, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_home", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_profile_to_search", label: "Search Tab", x: 25, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_search", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_profile_to_settings", label: "Settings Tab", x: 75, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_settings", transitionType: "push" }),
      ],
    },
    {
      id: "tpl_tab_settings",
      name: "Settings",
      x: MERGE_GAP * 3,
      y: 0,
      width: 220,
      imageData: settingsTabScreen(),
      description: "App settings tab with preferences and configuration",
      notes: "",
      codeRef: "",
      status: "new",
      acceptanceCriteria: [],
      stateGroup: null,
      stateName: "",
      tbd: false,
      tbdNote: "",
      roles: [],
      figmaSource: null,
      hotspots: [
        makeHotspot({ id: "tpl_tab_hs_settings_to_home", label: "Home Tab", x: 0, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_home", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_settings_to_search", label: "Search Tab", x: 25, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_search", transitionType: "push" }),
        makeHotspot({ id: "tpl_tab_hs_settings_to_profile", label: "Profile Tab", x: 50, y: 88, w: 25, h: 8, targetScreenId: "tpl_tab_profile", transitionType: "push" }),
      ],
    },
  ],
  connections: [
    {
      id: "tpl_tab_conn_home_to_search",
      fromScreenId: "tpl_tab_home",
      toScreenId: "tpl_tab_search",
      hotspotId: "tpl_tab_hs_home_to_search",
      label: "Search Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_home_to_profile",
      fromScreenId: "tpl_tab_home",
      toScreenId: "tpl_tab_profile",
      hotspotId: "tpl_tab_hs_home_to_profile",
      label: "Profile Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_home_to_settings",
      fromScreenId: "tpl_tab_home",
      toScreenId: "tpl_tab_settings",
      hotspotId: "tpl_tab_hs_home_to_settings",
      label: "Settings Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_search_to_home",
      fromScreenId: "tpl_tab_search",
      toScreenId: "tpl_tab_home",
      hotspotId: "tpl_tab_hs_search_to_home",
      label: "Home Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_search_to_profile",
      fromScreenId: "tpl_tab_search",
      toScreenId: "tpl_tab_profile",
      hotspotId: "tpl_tab_hs_search_to_profile",
      label: "Profile Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_search_to_settings",
      fromScreenId: "tpl_tab_search",
      toScreenId: "tpl_tab_settings",
      hotspotId: "tpl_tab_hs_search_to_settings",
      label: "Settings Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_profile_to_home",
      fromScreenId: "tpl_tab_profile",
      toScreenId: "tpl_tab_home",
      hotspotId: "tpl_tab_hs_profile_to_home",
      label: "Home Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_profile_to_search",
      fromScreenId: "tpl_tab_profile",
      toScreenId: "tpl_tab_search",
      hotspotId: "tpl_tab_hs_profile_to_search",
      label: "Search Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_profile_to_settings",
      fromScreenId: "tpl_tab_profile",
      toScreenId: "tpl_tab_settings",
      hotspotId: "tpl_tab_hs_profile_to_settings",
      label: "Settings Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_settings_to_home",
      fromScreenId: "tpl_tab_settings",
      toScreenId: "tpl_tab_home",
      hotspotId: "tpl_tab_hs_settings_to_home",
      label: "Home Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_settings_to_search",
      fromScreenId: "tpl_tab_settings",
      toScreenId: "tpl_tab_search",
      hotspotId: "tpl_tab_hs_settings_to_search",
      label: "Search Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
    {
      id: "tpl_tab_conn_settings_to_profile",
      fromScreenId: "tpl_tab_settings",
      toScreenId: "tpl_tab_profile",
      hotspotId: "tpl_tab_hs_settings_to_profile",
      label: "Profile Tab",
      action: "navigate",
      transitionType: "push",
      transitionLabel: "",
      dataFlow: [],
      connectionPath: "default",
      condition: "",
      conditionGroupId: null,
    },
  ],
  documents: [],
};
