export const COLORS = {
  bg: "#0a0a0f",
  surface: "#13131a",
  surfaceHover: "#1a1a24",
  border: "#2a2a3a",
  borderActive: "#6c5ce7",
  accent: "#6c5ce7",
  accentGlow: "rgba(108, 92, 231, 0.3)",
  accentLight: "#a29bfe",
  text: "#e8e8f0",
  textMuted: "#7a7a8e",
  textDim: "#4a4a5e",
  danger: "#ff6b6b",
  success: "#00d2d3",
  warning: "#feca57",
  canvasBg: "#08080d",
  canvasDot: "#1a1a28",
  screenBg: "#1e1e2e",
  hotspot: "rgba(108, 92, 231, 0.25)",
  hotspotBorder: "#6c5ce7",
  connectionLine: "#6c5ce7",
  condition: "#f0932b",
};

export const FONTS = {
  ui: "'Outfit', sans-serif",
  mono: "'JetBrains Mono', monospace",
  heading: "'Space Grotesk', sans-serif",
};

export const FONT_LINK =
  "https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;600&family=Space+Grotesk:wght@400;500;600;700&display=swap";

export const styles = {
  monoLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontFamily: FONTS.mono,
  },
  input: {
    display: "block",
    width: "100%",
    marginTop: 6,
    padding: "10px 12px",
    background: COLORS.bg,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    color: COLORS.text,
    fontSize: 13,
    fontFamily: FONTS.mono,
    outline: "none",
    boxSizing: "border-box",
  },
  select: {
    display: "block",
    width: "100%",
    marginTop: 6,
    padding: "10px 12px",
    background: COLORS.bg,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    color: COLORS.text,
    fontSize: 13,
    fontFamily: FONTS.mono,
    outline: "none",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.7)",
    backdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalCard: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 16,
    padding: 28,
    boxShadow: "0 20px 60px rgba(0,0,0,0.6)",
  },
  modalTitle: {
    margin: "0 0 20px",
    color: COLORS.text,
    fontFamily: FONTS.heading,
    fontSize: 18,
    fontWeight: 600,
  },
  btnPrimary: {
    padding: "10px 0",
    background: COLORS.accent,
    border: "none",
    borderRadius: 8,
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: FONTS.mono,
  },
  btnCancel: {
    padding: "10px 18px",
    background: "transparent",
    border: `1px solid ${COLORS.border}`,
    borderRadius: 8,
    color: COLORS.textMuted,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: FONTS.mono,
  },
  btnDanger: {
    padding: "10px 18px",
    background: "rgba(255,107,107,0.1)",
    border: "1px solid rgba(255,107,107,0.3)",
    borderRadius: 8,
    color: COLORS.danger,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: FONTS.mono,
  },
};
